$color0 = 474651
$color1 = 121D4E
$color2 = 7642E4
$color3 = 7A7752
$color4 = EB78EC
$color5 = 95ADDB
$color6 = B7FDFD
$color7 = D3F6F6
$color8 = 93ACAC
$color9 = 121D4E
$color10 = 7642E4
$color11 = 7A7752
$color12 = EB78EC
$color13 = 95ADDB
$color14 = B7FDFD
$color15 = D3F6F6
$colorBackground = 21212A
$colorForeground = E6FEFE
$colorCursor = AEA0F1
